---
- hosts: all
  remote_user: root
  vars:
  tasks:
  - name:  copy python script 
    sudo:  yes
    template:  src=pingall.py dest=/home/vagrant/
    when:  inventory_hostname == "playserver"

  - name:  copy pinglist file
    sudo:  yes
    template:  src=pinglist dest=/home/vagrant/
    when:  inventory_hostname == "playserver"

  - name:  create an entry in hosts file 
    sudo:  yes 
    lineinfile:  dest=/etc/hosts line="192.168.118.1  playserver"
    when:  inventory_hostname == "playserver"

  - name:  create an entry in hosts file
    sudo:  yes  
    lineinfile:  dest=/etc/hosts line="192.168.118.100  switch01"
    when:  inventory_hostname == "playserver"

  - name:  create an entry in hosts file
    sudo:  yes
    lineinfile:  dest=/etc/hosts line="192.168.119.100  switch02"
    when:  inventory_hostname == "playserver"


